services:

  json-server:
    image: vimagick/json-server
    build: .
    #command: json-server --watch ./config/db.json --port 8080 --host 0.0.0.0
    #command: --watch -h 0.0.0.0 -p 8080 /config/db.json
    command: npx json-server ./config/db.json -p 8080 -h 0.0.0.0
    stop_grace_period: 1s
    ports:
      - "8080:8080"
    volumes:
      - .:/config:/config

  numerator-api:
    image: node:20-alpine
    build: .
    command: node ./numerator-api/api.js
    stop_grace_period: 1s
    #working_dir: /numerator-api
    ports:
      - "3000:3000"
    volumes:
      - ./numerator-api:/numerator-api

  payments-api:
    image: node:20-alpine
    build: .
    command: node ./payments-api/index.js
    stop_grace_period: 1s
    #working_dir: /payments-api
    ports:
      - "3002:3002"
    volumes:
      - ./payments-api:/payments-api
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    #network_mode: bridge
    ports:
      - 6379:6379
    expose:
      - "6379"

  tcpdump:
    image: alpine
    command: sh -c "apk add --no-cache ngrep && ngrep -l -s 200000 -d any -W byline -q -t '^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS) ' port 8080"
    stop_grace_period: 1s
    network_mode: "service:json-server"